// Generated by CoffeeScript 2.5.1
(function() {
  var datas, extract_data, fs, jsonformat, jsontos, result;

  datas = require('./cryptos.json');

  fs = require('fs');

  result = {};

  extract_data = function(keyword, data) {
    var crypto, i, j, k, kw, l, len, len1, len2, len3, ref, ref1, ref2, ref3, ret, soustab, tab_tags, tag, tags, x;
    ret = {
      'name': keyword,
      'children': []
    };
    ref = Object.keys(data);
    for (i = 0, len = ref.length; i < len; i++) {
      crypto = ref[i];
      if (data[crypto].tags.length === 0) {
        ret.children.push({
          'name': crypto,
          'value': 1
        });
        delete data[crypto];
      }
    }
    while (Object.keys(data).length > 0) {
      tags = {};
      ref1 = Object.keys(data);
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        x = ref1[j];
        ref2 = data[x].tags;
        for (k = 0, len2 = ref2.length; k < len2; k++) {
          tag = ref2[k];
          if (tags[tag] != null) {
            tags[tag] = tags[tag] + 1;
            console.log("++");
          } else {
            tags[tag] = 1;
            console.log("00");
          }
        }
      }
      console.log("Element à trier : " + Object.keys(data).length);
      console.log(tags);
      if (Object.keys(data).length === 1) {
        console.log(Object.entries(data));
      }
      tab_tags = Object.entries(tags).sort(function(a, b) {
        return b[1] - a[1];
      });
      kw = tab_tags[0][0];
      console.log("Elected KW" + kw + "with :" + tab_tags[0][1]);
      soustab = {};
      ref3 = Object.keys(data);
      for (l = 0, len3 = ref3.length; l < len3; l++) {
        x = ref3[l];
        if (data[x]["tags"].includes(kw)) {
          soustab[x] = data[x];
          soustab[x]["tags"].splice(soustab[x]["tags"].indexOf(kw), 1);
          delete data[x];
        }
      }
      ret.children.push(extract_data(kw, soustab));
    }
    return ret;
  };

  jsonformat = extract_data("root", datas);

  console.log(jsonformat);

  jsontos = JSON.stringify(jsonformat, null, 2);

  fs.writeFileSync("arbre-tag.json", jsontos);

}).call(this);

//# sourceMappingURL=crytpostoD3coffee.js.map
